### ISSUE TITLE
Use classes instead of hardcoded element-styles

### ISSUE THREAD

**Issue by wdanilo** [hypertrack/gitbook-plugin-alerts#1]
Hi!
Current design of this plugin makes it impossible to override the colors and customize it to suit a custom theme. There are no separate classes for info / warning / error cards so we cannot refer them from CSS. 
Would you be so nice and provide a fix for it? It should be straightforward to introduce I think.

Looking forward to hearing from you,
Wojciech Danilo

**Comment by arjun27** [comment]
hey @wdanilo, thanks for checking out the plugin. would love to support this. let me get back to you with a timeline

**Comment by arjun27** [comment]
@wdanilo - this has been shipped. v0.2.0 of the plugin supports classes for css modification. hope this helps!

**Comment by wdanilo** [comment]
I'm very nicely surprised how fast you've addressed this issue. Thank you very much, I really appreciate it!
