### ISSUE TITLE
impossible to put multiple consecutive bloc of the same type

### ISSUE THREAD

**Issue by pmusset** [hypertrack/gitbook-plugin-alerts#3]
Hello,

It is actually impossible to put multiple bloc of the same type following one another.
When I try it puts everything into only one `<blockquote></blockquote>`.
Is it possible to correct that or maybe I am trying something wrong?

Paul

**Comment by arjun27** [comment]
Hey @pmusset, I believe you are right, it wouldn't render consecutive blocks correctly. I would recommend trying using `&nbsp;` as a delimiter between the two blocks.

```
> block 1
&nbsp;
> block 2
```

Let me know if this works for your needs.

**Comment by pmusset** [comment]
Hey,
Thanks for the quick answer. it worked with 
```
> block 1

&nbsp;

> block 2
```
the empty line being just new lines.
Maybe write it somewhere in the README.
